" Vundle settings
set nocompatible              " be iMproved, required
filetype off                  " required

" Set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Github plugins
Plugin 'preservim/nerdtree'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" Scheme settings
syntax on

" For Vim 7
set t_Co=256

" For Vim 8
if (has("termguicolors"))
  set termguicolors
endif

let g:oceanic_next_terminal_bold = 1
let g:oceanic_next_terminal_italic = 1

hi Normal guibg=NONE ctermbg=NONE
hi MatchParen cterm=bold ctermbg=black ctermfg=darkgreen

let python_highlight_all = 1

colorscheme OceanicNext

" Search settings
set showmatch
set hlsearch
set incsearch
set smartcase
set ignorecase

" Tabs, indent settings
set tabstop=4
set shiftwidth=4
set showtabline=1
set smarttab
set expandtab
set autoindent
set wrap
set linebreak
set textwidth=80

" Enables smartindent after keywords in Python files
autocmd BufRead *.py set smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class

" Enables smartbackspace
set backspace=indent,eol,start

" Disables automatic commenting on new line
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" Splits open at the bottom and right
set splitbelow splitright

" Shortcutting split navigation, saving a keypress
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <c-l> <C-w>l

" New tab is aliased to Ctrl+t
nnoremap <silent> <C-t> :tabnew<CR>

" Set default clipboard to the system clipboard
set clipboard=unnamedplus

" Past from system clipboard with ctrl+i instead of shift+insert
map <S-Insert> <C-i>
map! <S-Insert> <C-i>

" Automatically deletes all trailing whitespace on save
autocmd BufWritePre * %s/\s\+$//e

" Global replace is aliased to S
nnoremap S :%s//g<Left><Left>

" Enables spellchecker
map <F5> :setlocal spell! spelllang=en_us,ru_yo<CR>

" File settings
set encoding=utf-8
set fileencodings=utf-8,cp1251
set fileformat=unix

" Disables backups and swap files
set nobackup
set noswapfile

" Other VIM shiiit
set number relativenumber
set undolevels=1000
set termencoding=utf-8

